INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (1, 'Tinte', '68981');
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (2, 'Permanente', '25672');
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (3, 'Permanente', '89146');
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (4, 'Depilación facial', '21656');
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (5, 'Extensiones', '31278');
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (6, 'Mechas', '85218');
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (7, 'Maquillaje', '20095');
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (8, 'Permanente', '52126');
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (9, 'Maquillaje', '45368');
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (10, 'Manicura', '16320');
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (11, 'Tinte', '81569');
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (12, 'Depilación facial', '75281');
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (13, 'Tratamiento capilar', '31710');
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (14, 'Tratamiento capilar', '36017');
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (15, 'Pedicura', '54044');
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (16, 'Pedicura', '92966');
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (17, 'Manicura', '45220');
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (18, 'Tratamiento capilar', '98244');
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (19, 'Tinte', '65427');
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (20, 'Alisado', '21509');