INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Gel Fijador', 16990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Espuma de Peinar', 14990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Acondicionador Reparador', 14990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Crema de Peinado', 19990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Champu Anticaspa', 24990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Serum Anticaida', 14990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Champu Voluminizador', 8990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Espuma de Peinar', 24990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Champu Voluminizador', 12990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Champu Voluminizador', 5990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Shampoo Hidratante', 19990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Crema Rizadora', 5990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Espuma de Peinar', 10990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Espuma de Peinar', 10990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Aceite Capilar', 7990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Espuma de Peinar', 8990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Serum Anticaida', 8990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Crema Alisadora', 4990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Cepillo para Cabello', 16990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Cepillo para Cabello', 6990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Serum Anticaida', 10990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Shampoo Hidratante', 19990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Champu Voluminizador', 10990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Champu Voluminizador', 11990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Crema Rizadora', 5990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Cepillo para Cabello', 4990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Shampoo Hidratante', 8990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Champu Voluminizador', 12990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Laca para Cabello', 14990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Crema Alisadora', 7990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Cera para Cabello', 16990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Mascarilla Capilar', 14990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Gel Fijador', 8990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Acondicionador Reparador', 24990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Tinte Capilar Castano', 19990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Tinte Capilar Castano', 11990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Cera para Cabello', 16990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Aceite Capilar', 4990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Mascarilla Nutritiva', 14990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Crema Rizadora', 12990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Shampoo Hidratante', 16990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Aceite Capilar', 11990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Espuma de Peinar', 16990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Tinte Capilar Negro', 12990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Champu Anticaspa', 7990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Crema Alisadora', 19990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Gel Fijador', 14990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Cepillo para Cabello', 7990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Serum Anticaida', 14990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Serum Anticaida', 19990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Spray Protector Termico', 24990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Espuma de Peinar', 19990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Crema Alisadora', 8990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Mascarilla Capilar', 8990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Cera para Cabello', 8990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Espuma de Peinar', 16990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Crema de Peinado', 16990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Tinte Capilar Rubio', 8990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Crema de Peinado', 8990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Cepillo para Cabello', 12990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Spray Protector Termico', 19990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Espuma de Peinar', 9990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Tinte Capilar Negro', 14990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Champu Voluminizador', 4990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Champu Anticaspa', 14990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Mascarilla Nutritiva', 19990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Crema Rizadora', 24990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Crema Alisadora', 6990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Gel Fijador', 8990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Aceite Capilar', 24990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Tinte Capilar Rubio', 14990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Mascarilla Nutritiva', 9990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Tinte Capilar Castano', 19990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Tinte Capilar Negro', 8990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Crema Alisadora', 9990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Champu Voluminizador', 12990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Cepillo para Cabello', 12990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Champu Anticaspa', 19990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Tinte Capilar Rubio', 8990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Gel Fijador', 5990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Mascarilla Nutritiva', 19990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Cepillo para Cabello', 16990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Espuma de Peinar', 8990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Gel Fijador', 11990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Tinte Capilar Castano', 8990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Espuma de Peinar', 14990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Crema Alisadora', 14990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Acondicionador Reparador', 6990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Mascarilla Nutritiva', 14990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Serum Anticaida', 9990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Crema Rizadora', 5990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Tinte Capilar Negro', 19990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Tinte Capilar Rubio', 16990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Mascarilla Capilar', 19990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Champu Voluminizador', 4990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Cera para Cabello', 12990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Mascarilla Capilar', 24990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Crema Rizadora', 4990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Shampoo Hidratante', 19990);
INSERT INTO producto (nombre_prod, precio_prod) VALUES ('Espuma de Peinar', 12990);