INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('1', 'Gel Fijador', 5990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('2', 'Serum Anticaida', 12990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('3', 'Aceite Capilar', 19990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('4', 'Mascarilla Capilar', 24990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('5', 'Laca para Cabello', 19990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('6', 'Espuma de Peinar', 11990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('7', 'Shampoo Hidratante', 16990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('8', 'Mascarilla Nutritiva', 8990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('9', 'Espuma de Peinar', 7990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('10', 'Tinte Capilar Castano', 9990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('11', 'Spray Protector Termico', 9990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('12', 'Mascarilla Nutritiva', 11990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('13', 'Champu Anticaspa', 7990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('14', 'Aceite Capilar', 4990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('15', 'Tinte Capilar Castano', 7990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('16', 'Champu Voluminizador', 14990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('17', 'Laca para Cabello', 9990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('18', 'Crema de Peinado', 14990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('19', 'Crema Alisadora', 12990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('20', 'Crema Rizadora', 8990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('21', 'Espuma de Peinar', 6990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('22', 'Crema Alisadora', 8990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('23', 'Espuma de Peinar', 12990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('24', 'Serum Anticaida', 14990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('25', 'Mascarilla Capilar', 6990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('26', 'Laca para Cabello', 9990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('27', 'Gel Fijador', 5990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('28', 'Tinte Capilar Negro', 12990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('29', 'Serum Anticaida', 11990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('30', 'Mascarilla Nutritiva', 6990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('31', 'Champu Voluminizador', 10990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('32', 'Serum Anticaida', 4990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('33', 'Mascarilla Nutritiva', 11990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('34', 'Laca para Cabello', 12990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('35', 'Tinte Capilar Castano', 7990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('36', 'Tinte Capilar Rubio', 14990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('37', 'Acondicionador Reparador', 14990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('38', 'Aceite Capilar', 12990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('39', 'Mascarilla Capilar', 16990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('40', 'Espuma de Peinar', 16990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('41', 'Shampoo Hidratante', 4990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('42', 'Cepillo para Cabello', 16990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('43', 'Espuma de Peinar', 12990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('44', 'Acondicionador Reparador', 16990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('45', 'Crema de Peinado', 16990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('46', 'Acondicionador Reparador', 19990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('47', 'Tinte Capilar Castano', 6990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('48', 'Cera para Cabello', 12990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('49', 'Mascarilla Capilar', 11990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('50', 'Tinte Capilar Rubio', 14990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('51', 'Crema Alisadora', 12990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('52', 'Cepillo para Cabello', 19990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('53', 'Crema de Peinado', 14990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('54', 'Spray Protector Termico', 8990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('55', 'Crema Rizadora', 12990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('56', 'Laca para Cabello', 9990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('57', 'Spray Protector Termico', 11990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('58', 'Mascarilla Capilar', 19990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('59', 'Shampoo Hidratante', 19990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('60', 'Champu Voluminizador', 16990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('61', 'Acondicionador Reparador', 9990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('62', 'Crema Rizadora', 8990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('63', 'Espuma de Peinar', 19990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('64', 'Acondicionador Reparador', 9990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('65', 'Spray Protector Termico', 24990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('66', 'Espuma de Peinar', 8990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('67', 'Acondicionador Reparador', 9990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('68', 'Champu Anticaspa', 19990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('69', 'Mascarilla Capilar', 4990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('70', 'Tinte Capilar Castano', 12990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('71', 'Espuma de Peinar', 9990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('72', 'Crema de Peinado', 4990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('73', 'Crema Alisadora', 12990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('74', 'Mascarilla Nutritiva', 9990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('75', 'Tinte Capilar Rubio', 4990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('76', 'Espuma de Peinar', 19990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('77', 'Crema de Peinado', 9990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('78', 'Spray Protector Termico', 5990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('79', 'Acondicionador Reparador', 24990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('80', 'Cera para Cabello', 14990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('81', 'Serum Anticaida', 4990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('82', 'Champu Anticaspa', 12990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('83', 'Acondicionador Reparador', 12990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('84', 'Serum Anticaida', 14990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('85', 'Gel Fijador', 19990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('86', 'Spray Protector Termico', 19990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('87', 'Aceite Capilar', 14990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('88', 'Champu Anticaspa', 16990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('89', 'Tinte Capilar Negro', 24990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('90', 'Tinte Capilar Castano', 6990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('91', 'Aceite Capilar', 6990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('92', 'Crema Alisadora', 8990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('93', 'Champu Voluminizador', 19990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('94', 'Gel Fijador', 4990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('95', 'Crema de Peinado', 16990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('96', 'Crema Alisadora', 19990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('97', 'Spray Protector Termico', 7990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('98', 'Aceite Capilar', 7990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('99', 'Mascarilla Nutritiva', 4990);
INSERT INTO producto (id_prod, nombre_prod, precio_prod) VALUES ('100', 'Aceite Capilar', 16990);