INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (1, 'Corte varon', 4612);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (2, 'Corte mujer', 25409);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (3, 'Corte barba', 23827);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (4, 'Tinte completo', 20677);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (5, 'Mechas', 92811);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (6, 'Balayage', 27816);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (7, 'Alisado de keratina', 29619);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (8, 'Permanente', 61533);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (9, 'Lavado y peinado', 90693);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (10, 'Recogido para eventos', 96066);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (11, 'Tratamiento capilar nutritivo', 14501);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (12, 'Extensiones de cabello', 11536);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (13, 'Coloración de raices', 45498);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (14, 'Corte y peinado infantil', 52125);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (15, 'Tratamiento anticaída', 66146);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (16, 'Desrizado', 57318);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (17, 'Tratamiento de hidratacion profunda', 40931);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (18, 'Masaje capilar', 79487);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (19, 'Peinado para novias', 43323);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (20, 'Tratamiento detox capilar', 32926);