INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('1', 'Serum Anticaida', 5990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('2', 'Crema de Peinado', 6990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('3', 'Champu Anticaspa', 19990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('4', 'Espuma de Peinar', 9990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('5', 'Tinte Capilar Rubio', 9990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('6', 'Tinte Capilar Castano', 12990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('7', 'Cepillo para Cabello', 14990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('8', 'Mascarilla Capilar', 9990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('9', 'Mascarilla Capilar', 9990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('10', 'Crema Rizadora', 12990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('11', 'Spray Protector Termico', 8990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('12', 'Cepillo para Cabello', 6990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('13', 'Crema Alisadora', 12990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('14', 'Spray Protector Termico', 19990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('15', 'Mascarilla Capilar', 14990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('16', 'Tinte Capilar Castano', 9990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('17', 'Aceite Capilar', 9990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('18', 'Crema Alisadora', 6990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('19', 'Shampoo Hidratante', 14990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('20', 'Spray Protector Termico', 9990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('21', 'Champu Anticaspa', 6990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('22', 'Tinte Capilar Rubio', 8990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('23', 'Tinte Capilar Castano', 14990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('24', 'Mascarilla Capilar', 16990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('25', 'Espuma de Peinar', 12990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('26', 'Acondicionador Reparador', 16990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('27', 'Shampoo Hidratante', 19990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('28', 'Crema Alisadora', 19990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('29', 'Champu Anticaspa', 6990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('30', 'Laca para Cabello', 14990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('31', 'Mascarilla Capilar', 7990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('32', 'Acondicionador Reparador', 7990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('33', 'Champu Voluminizador', 19990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('34', 'Tinte Capilar Castano', 10990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('35', 'Tinte Capilar Negro', 14990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('36', 'Mascarilla Capilar', 19990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('37', 'Tinte Capilar Negro', 14990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('38', 'Tinte Capilar Castano', 6990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('39', 'Champu Voluminizador', 24990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('40', 'Tinte Capilar Castano', 19990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('41', 'Tinte Capilar Rubio', 19990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('42', 'Shampoo Hidratante', 24990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('43', 'Espuma de Peinar', 11990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('44', 'Laca para Cabello', 6990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('45', 'Champu Anticaspa', 14990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('46', 'Champu Anticaspa', 14990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('47', 'Crema Alisadora', 9990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('48', 'Shampoo Hidratante', 4990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('49', 'Shampoo Hidratante', 11990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('50', 'Crema de Peinado', 14990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('51', 'Tinte Capilar Castano', 19990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('52', 'Cera para Cabello', 24990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('53', 'Shampoo Hidratante', 19990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('54', 'Mascarilla Capilar', 12990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('55', 'Crema de Peinado', 12990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('56', 'Tinte Capilar Negro', 16990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('57', 'Mascarilla Nutritiva', 16990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('58', 'Crema de Peinado', 8990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('59', 'Crema Rizadora', 6990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('60', 'Cera para Cabello', 24990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('61', 'Tinte Capilar Castano', 10990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('62', 'Serum Anticaida', 8990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('63', 'Acondicionador Reparador', 8990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('64', 'Crema de Peinado', 19990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('65', 'Tinte Capilar Negro', 24990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('66', 'Spray Protector Termico', 16990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('67', 'Espuma de Peinar', 5990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('68', 'Shampoo Hidratante', 8990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('69', 'Crema Rizadora', 14990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('70', 'Aceite Capilar', 4990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('71', 'Gel Fijador', 8990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('72', 'Aceite Capilar', 14990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('73', 'Laca para Cabello', 12990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('74', 'Crema Alisadora', 5990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('75', 'Champu Voluminizador', 14990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('76', 'Aceite Capilar', 9990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('77', 'Cera para Cabello', 24990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('78', 'Serum Anticaida', 8990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('79', 'Cepillo para Cabello', 6990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('80', 'Champu Anticaspa', 19990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('81', 'Tinte Capilar Rubio', 11990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('82', 'Champu Anticaspa', 11990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('83', 'Tinte Capilar Castano', 16990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('84', 'Shampoo Hidratante', 5990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('85', 'Aceite Capilar', 19990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('86', 'Crema Alisadora', 19990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('87', 'Mascarilla Capilar', 8990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('88', 'Aceite Capilar', 11990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('89', 'Cera para Cabello', 8990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('90', 'Tinte Capilar Rubio', 5990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('91', 'Tinte Capilar Negro', 5990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('92', 'Laca para Cabello', 19990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('93', 'Champu Anticaspa', 12990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('94', 'Laca para Cabello', 5990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('95', 'Crema Rizadora', 19990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('96', 'Aceite Capilar', 14990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('97', 'Gel Fijador', 8990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('98', 'Shampoo Hidratante', 19990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('99', 'Champu Voluminizador', 16990);
INSERT INTO producto (id_produ, nombre_prod, precio_prod) VALUES ('100', 'Espuma de Peinar', 16990);