INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (1, 'Tijeras de Oro', 'Callejón del Peinado 303', 'Osorno', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (2, 'Pelo Perfecto', 'Plaza de la Belleza 202', 'Rio Bueno', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (3, 'Rizos Perfectos', 'Callejón del Peinado 303', 'Villa Alemana', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (4, 'Estilo Único', 'Calle Estilo 505', 'Temuco', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (5, 'Pelo Perfecto', 'Avenida del Color 808', 'Las Condes', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (6, 'Brillo Natural', 'Calle del Comercio 456', 'Las Condes', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (7, 'Colores Vivos', 'Paseo de la Moda 789', 'Castro', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (8, 'Tijeras de Oro', 'Calle Estilo 505', 'Puerto Montt', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (9, 'Estilo Único', 'Callejón del Peinado 303', 'Concon', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (10, 'Esencia Capilar', 'Boulevard Estilista 101', 'Taltal', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (11, 'Glamour Hair', 'Avenida del Color 808', 'Castro', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (12, 'Brillo Natural', 'Plaza de la Belleza 202', 'Taltal', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (13, 'Ondas y Más', 'Avenida Glamour 404', 'Angol', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (14, 'Mechones Divinos', 'Calle del Secador 909', 'Puerto Varas', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (15, 'Brillo Natural', 'Calle del Comercio 456', 'Puerto Montt', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (16, 'Pelo Perfecto', 'Paseo del Rizo 222', 'Osorno', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (17, 'Estilo Único', 'Avenida Glamour 404', 'Puerto Montt', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (18, 'Estilo Urbano', 'Avenida Glamour 404', 'Los Angeles', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (19, 'Rizos Perfectos', 'Camino de las Tijeras 707', 'Angol', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (20, 'Corte Elegante', 'Plaza de la Belleza 202', 'Victoria', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (21, 'Rizos Perfectos', 'Calle Estilo 505', 'Valparaiso', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (22, 'Esencia Capilar', 'Avenida Glamour 404', 'Osorno', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (23, 'Tijeras de Oro', 'Paseo de la Moda 789', 'Las Condes', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (24, 'Brillo Natural', 'Pasaje del Espejo 606', 'Santiago', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (25, 'Corte Elegante', 'Calle del Secador 909', 'Puerto Montt', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (26, 'Mechones Divinos', 'Camino de las Tijeras 707', 'Maipu', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (27, 'Estilo Único', 'Avenida de la Creatividad 333', 'Mariquina', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (28, 'Colores Vivos', 'Calle del Secador 909', 'Antofagasta', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (29, 'Cortes Mágicos', 'Paseo del Rizo 222', 'Castro', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (30, 'Belleza Total', 'Calle Estilo 505', 'La Union', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (31, 'Estilo Urbano', 'Avenida de la Creatividad 333', 'Los Angeles', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (32, 'Cortes Mágicos', 'Calle Estilo 505', 'Corral', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (33, 'Rizos Perfectos', 'Calle del Secador 909', 'Puerto Montt', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (34, 'Brillo Natural', 'Calle del Comercio 456', 'Mejillones', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (35, 'Estilo Único', 'Boulevard Estilista 101', 'Mejillones', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (36, 'Estilo Urbano', 'Callejón del Peinado 303', 'Chillan', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (37, 'Colores Vivos', 'Avenida del Color 808', 'Quilpue', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (38, 'Estilo Urbano', 'Plaza de la Belleza 202', 'Lautaro', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (39, 'Ondas y Más', 'Avenida Glamour 404', 'Quilpue', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (40, 'Mechones Divinos', 'Paseo de la Moda 789', 'Osorno', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (41, 'Glamour Hair', 'Paseo del Rizo 222', 'Osorno', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (42, 'Ondas y Más', 'Calle Estilo 505', 'Valparaiso', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (43, 'Belleza Total', 'Callejón del Peinado 303', 'Osorno', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (44, 'Estilo Único', 'Callejón del Peinado 303', 'Santiago', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (45, 'Cabello de Ensueño', 'Camino de las Tijeras 707', 'Valparaiso', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (46, 'Esencia Capilar', 'Avenida Glamour 404', 'Mafil', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (47, 'Cabello de Ensueño', 'Avenida Glamour 404', 'Las Condes', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (48, 'Glamour Hair', 'Pasaje del Espejo 606', 'Taltal', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (49, 'Mechones Divinos', 'Calle Estilo 505', 'Los Angeles', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (50, 'Estilo Urbano', 'Avenida del Color 808', 'Calama', 'Antofagasta');