INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (1, 'Tratamiento capilar', $54800.00);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (2, 'Corte de cabello', $95000.00);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (3, 'Peinado', $29000.00);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (4, 'Depilación facial', $17300.00);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (5, 'Mechas', $28700.00);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (6, 'Manicura', $21900.00);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (7, 'Recogido', $87100.00);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (8, 'Maquillaje', $95500.00);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (9, 'Alisado', $75800.00);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (10, 'Manicura', $42600.00);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (11, 'Permanente', $86500.00);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (12, 'Extensiones', $15900.00);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (13, 'Permanente', $10200.00);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (14, 'Mechas', $6400.00);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (15, 'Recogido', $42100.00);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (16, 'Corte de cabello', $83500.00);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (17, 'Recogido', $48600.00);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (18, 'Manicura', $45800.00);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (19, 'Tratamiento capilar', $18100.00);
INSERT INTO servicio (id_serv, tipo_serv, precio_serv) VALUES (20, 'Lavado y secado', $54700.00);