INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (601, 'Peluqueria 22', 'Avenida Independencia 707', 'Villarrica', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (657, 'Peluqueria 97', 'Avenida Recoleta 222', 'Concepcion', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (372, 'Peluqueria 40', 'Calle Suecia 555', 'Coronel', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (64, 'Peluqueria 78', 'Calle San Diego 808', 'Quilpue', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (219, 'Peluqueria 39', 'Calle San Diego 808', 'Mafil', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (298, 'Peluqueria 90', 'Avenida Brasil 505', 'Calama', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (441, 'Peluqueria 82', 'Avenida OHiggins 444', 'Concepcion', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (987, 'Peluqueria 51', 'Pasaje Olvidado 789', 'Angol', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (634, 'Peluqueria 50', 'Calle Bellavista 606', 'Antofagasta', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (124, 'Peluqueria 72', 'Boulevard Eterno 753', 'Providencia', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (742, 'Peluqueria 26', 'Camino Perdido 159', 'Providencia', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (998, 'Peluqueria 21', 'Paseo Bulnes 303', 'Lautaro', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (310, 'Peluqueria 70', 'Calle Esmeralda 333', 'Corral', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (268, 'Peluqueria 76', 'Calle Merced 111', 'Calama', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (717, 'Peluqueria 69', 'Avenida Recoleta 222', 'Rio Bueno', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (26, 'Peluqueria 38', 'Avenida Siempre Viva 456', 'Temuco', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (872, 'Peluqueria 38', 'Pasaje Olvidado 789', 'Lanco', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (844, 'Peluqueria 41', 'Calle Suecia 555', 'Villarrica', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (206, 'Peluqueria 67', 'Camino Perdido 159', 'Valparaiso', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (230, 'Peluqueria 86', 'Avenida Brasil 505', 'Villarrica', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (887, 'Peluqueria 76', 'Avenida Santa Rosa 909', 'Villarrica', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (163, 'Peluqueria 68', 'Avenida OHiggins 444', 'Quilpue', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (358, 'Peluqueria 48', 'Calle Bellavista 606', 'Providencia', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (31, 'Peluqueria 48', 'Avenida Independencia 707', 'Quilpue', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (514, 'Peluqueria 88', 'Avenida Independencia 707', 'Castro', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (291, 'Peluqueria 20', 'Avenida Matta 202', 'Calama', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (182, 'Peluqueria 41', 'Avenida Matta 202', 'Rio Bueno', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (857, 'Peluqueria 13', 'Avenida Santa Rosa 909', 'Valdivia', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (344, 'Peluqueria 93', 'Calle Merced 111', 'Puerto Varas', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (307, 'Peluqueria 39', 'Avenida OHiggins 444', 'Temuco', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (357, 'Peluqueria 96', 'Calle San Diego 808', 'Mariquina', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (648, 'Peluqueria 63', 'Avenida Matta 202', 'Lautaro', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (163, 'Peluqueria 84', 'Calle San Diego 808', 'Temuco', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (432, 'Peluqueria 99', 'Calle Londres 404', 'Antofagasta', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (716, 'Peluqueria 41', 'Camino Perdido 159', 'Puerto Varas', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (864, 'Peluqueria 26', 'Avenida Matta 202', 'Providencia', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (849, 'Peluqueria 97', 'Pasaje Olvidado 789', 'Talcahuano', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (250, 'Peluqueria 76', 'Avenida Recoleta 222', 'Concon', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (82, 'Peluqueria 86', 'Pasaje Olvidado 789', 'Villa Alemana', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (507, 'Peluqueria 67', 'Calle Suecia 555', 'Tocopilla', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (647, 'Peluqueria 27', 'Calle San Diego 808', 'Las Condes', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (687, 'Peluqueria 29', 'Avenida Siempre Viva 456', 'Quilpue', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (807, 'Peluqueria 37', 'Avenida Siempre Viva 456', 'Valparaiso', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (353, 'Peluqueria 89', 'Calle Bellavista 606', 'Maipu', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (3, 'Peluqueria 35', 'Calle Esmeralda 333', 'Osorno', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (175, 'Peluqueria 97', 'Calle Bellavista 606', 'Villa Alemana', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (287, 'Peluqueria 96', 'Avenida Independencia 707', 'Victoria', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (808, 'Peluqueria 8', 'Avenida Santa Rosa 909', 'Villa Alemana', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (287, 'Peluqueria 51', 'Avenida Independencia 707', 'Santiago', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (16, 'Peluqueria 58', 'Calle Merced 111', 'Puerto Varas', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (940, 'Peluqueria 44', 'Avenida Siempre Viva 456', 'Quilpue', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (362, 'Peluqueria 52', 'Camino Perdido 159', 'Corral', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (312, 'Peluqueria 74', 'Avenida Siempre Viva 456', 'Villa Alemana', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (151, 'Peluqueria 1', 'Camino Perdido 159', 'Castro', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (264, 'Peluqueria 90', 'Avenida Recoleta 222', 'Maipu', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (73, 'Peluqueria 64', 'Avenida Recoleta 222', 'Temuco', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (109, 'Peluqueria 15', 'Calle San Diego 808', 'Maipu', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (80, 'Peluqueria 21', 'Avenida Tobalaba 666', 'Valparaiso', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (299, 'Peluqueria 64', 'Avenida Santa Rosa 909', 'Los Angeles', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (596, 'Peluqueria 23', 'Avenida Recoleta 222', 'Castro', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (265, 'Peluqueria 100', 'Avenida Tobalaba 666', 'Puerto Varas', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (680, 'Peluqueria 89', 'Avenida Siempre Viva 456', 'Valdivia', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (878, 'Peluqueria 66', 'Avenida Independencia 707', 'Temuco', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (529, 'Peluqueria 8', 'Calle Merced 111', 'Castro', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (692, 'Peluqueria 81', 'Camino Perdido 159', 'Tocopilla', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (837, 'Peluqueria 27', 'Avenida Siempre Viva 456', 'Puerto Varas', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (611, 'Peluqueria 50', 'Avenida Siempre Viva 456', 'Osorno', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (356, 'Peluqueria 33', 'Avenida Recoleta 222', 'Villa Alemana', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (551, 'Peluqueria 66', 'Avenida Independencia 707', 'Mejillones', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (369, 'Peluqueria 37', 'Boulevard Eterno 753', 'Talcahuano', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (292, 'Peluqueria 64', 'Calle Falsa 123', 'Tocopilla', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (351, 'Peluqueria 10', 'Calle Falsa 123', 'Maipu', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (877, 'Peluqueria 20', 'Calle Falsa 123', 'Villa Alemana', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (79, 'Peluqueria 71', 'Avenida Recoleta 222', 'Villa Alemana', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (990, 'Peluqueria 92', 'Avenida Recoleta 222', 'La Union', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (217, 'Peluqueria 40', 'Avenida Siempre Viva 456', 'Puerto Varas', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (685, 'Peluqueria 60', 'Avenida Siempre Viva 456', 'Las Condes', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (799, 'Peluqueria 91', 'Pasaje Olvidado 789', 'Antofagasta', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (207, 'Peluqueria 77', 'Calle Bellavista 606', 'Mejillones', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (37, 'Peluqueria 36', 'Calle Londres 404', 'Rio Bueno', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (538, 'Peluqueria 12', 'Paseo Bulnes 303', 'Victoria', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (39, 'Peluqueria 85', 'Avenida Lira 101', 'Calama', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (81, 'Peluqueria 85', 'Pasaje Olvidado 789', 'Mejillones', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (326, 'Peluqueria 66', 'Avenida Recoleta 222', 'Osorno', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (167, 'Peluqueria 70', 'Calle Falsa 123', 'Taltal', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (62, 'Peluqueria 87', 'Pasaje Olvidado 789', 'Talcahuano', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (558, 'Peluqueria 76', 'Calle Suecia 555', 'Puerto Varas', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (233, 'Peluqueria 15', 'Calle Merced 111', 'Talcahuano', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (538, 'Peluqueria 20', 'Avenida Lira 101', 'Valparaiso', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (303, 'Peluqueria 8', 'Avenida Lira 101', 'Las Condes', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (54, 'Peluqueria 61', 'Avenida Tobalaba 666', 'Lanco', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (175, 'Peluqueria 32', 'Calle Bellavista 606', 'La Union', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (27, 'Peluqueria 67', 'Avenida Independencia 707', 'Las Condes', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (171, 'Peluqueria 86', 'Avenida Siempre Viva 456', 'Concepcion', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (16, 'Peluqueria 80', 'Camino Perdido 159', 'Quilpue', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (88, 'Peluqueria 44', 'Avenida Lira 101', 'Los Angeles', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (135, 'Peluqueria 83', 'Calle Suecia 555', 'Valparaiso', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (736, 'Peluqueria 84', 'Avenida Recoleta 222', 'Antofagasta', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (923, 'Peluqueria 45', 'Avenida Brasil 505', 'Valparaiso', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (269, 'Peluqueria 74', 'Avenida Tobalaba 666', 'Los Angeles', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (920, 'Peluqueria 19', 'Calle San Diego 808', 'Lautaro', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (976, 'Peluqueria 69', 'Paseo Bulnes 303', 'Lanco', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (846, 'Peluqueria 12', 'Pasaje Olvidado 789', 'Los Angeles', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (612, 'Peluqueria 36', 'Avenida Santa Rosa 909', 'Taltal', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (838, 'Peluqueria 30', 'Avenida Matta 202', 'Providencia', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (931, 'Peluqueria 1', 'Camino Perdido 159', 'Puerto Montt', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (88, 'Peluqueria 34', 'Avenida Siempre Viva 456', 'Castro', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (322, 'Peluqueria 68', 'Avenida OHiggins 444', 'Coronel', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (351, 'Peluqueria 11', 'Calle San Diego 808', 'Concon', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (854, 'Peluqueria 47', 'Avenida Siempre Viva 456', 'Valparaiso', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (44, 'Peluqueria 51', 'Avenida Tobalaba 666', 'Lanco', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (345, 'Peluqueria 3', 'Calle Merced 111', 'Quilpue', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (994, 'Peluqueria 11', 'Avenida Santa Rosa 909', 'Puerto Varas', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (201, 'Peluqueria 72', 'Calle Merced 111', 'Valdivia', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (898, 'Peluqueria 24', 'Calle Londres 404', 'Puerto Varas', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (197, 'Peluqueria 70', 'Calle Suecia 555', 'Villarrica', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (269, 'Peluqueria 86', 'Avenida Siempre Viva 456', 'Puerto Varas', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (621, 'Peluqueria 52', 'Calle Esmeralda 333', 'Temuco', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (791, 'Peluqueria 11', 'Avenida Siempre Viva 456', 'Coronel', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (243, 'Peluqueria 95', 'Avenida Independencia 707', 'Mejillones', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (618, 'Peluqueria 80', 'Avenida Recoleta 222', 'Mejillones', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (501, 'Peluqueria 46', 'Calle Esmeralda 333', 'Los Angeles', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (750, 'Peluqueria 79', 'Paseo Bulnes 303', 'Puerto Montt', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (931, 'Peluqueria 90', 'Avenida Brasil 505', 'Puerto Montt', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (33, 'Peluqueria 66', 'Avenida Tobalaba 666', 'La Union', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (337, 'Peluqueria 93', 'Camino Perdido 159', 'Lanco', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (57, 'Peluqueria 25', 'Avenida Recoleta 222', 'Lanco', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (568, 'Peluqueria 11', 'Calle Merced 111', 'Quilpue', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (777, 'Peluqueria 81', 'Paseo Bulnes 303', 'Santiago', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (935, 'Peluqueria 48', 'Camino Perdido 159', 'Los Angeles', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (545, 'Peluqueria 2', 'Paseo Bulnes 303', 'Osorno', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (360, 'Peluqueria 87', 'Avenida Santa Rosa 909', 'Temuco', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (631, 'Peluqueria 63', 'Calle Bellavista 606', 'Concon', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (202, 'Peluqueria 12', 'Camino Perdido 159', 'Victoria', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (41, 'Peluqueria 86', 'Calle Merced 111', 'Los Angeles', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (773, 'Peluqueria 89', 'Calle Esmeralda 333', 'Villa Alemana', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (718, 'Peluqueria 79', 'Avenida OHiggins 444', 'Coronel', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (928, 'Peluqueria 18', 'Calle Bellavista 606', 'Puerto Montt', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (789, 'Peluqueria 77', 'Boulevard Eterno 753', 'Tocopilla', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (161, 'Peluqueria 36', 'Avenida OHiggins 444', 'Corral', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (804, 'Peluqueria 20', 'Avenida Siempre Viva 456', 'Maipu', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (422, 'Peluqueria 52', 'Avenida Lira 101', 'Villa Alemana', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (67, 'Peluqueria 45', 'Avenida Siempre Viva 456', 'Calama', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (254, 'Peluqueria 31', 'Avenida Santa Rosa 909', 'Santiago', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (957, 'Peluqueria 61', 'Avenida Independencia 707', 'Angol', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (111, 'Peluqueria 15', 'Avenida Siempre Viva 456', 'Las Condes', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (32, 'Peluqueria 73', 'Avenida Independencia 707', 'Valdivia', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (854, 'Peluqueria 31', 'Avenida OHiggins 444', 'Maipu', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (649, 'Peluqueria 90', 'Calle Falsa 123', 'Mejillones', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (546, 'Peluqueria 51', 'Calle Falsa 123', 'Lautaro', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (870, 'Peluqueria 8', 'Avenida Siempre Viva 456', 'Concepcion', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (598, 'Peluqueria 79', 'Avenida OHiggins 444', 'Mafil', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (344, 'Peluqueria 5', 'Camino Perdido 159', 'Mariquina', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (607, 'Peluqueria 21', 'Pasaje Olvidado 789', 'Victoria', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (550, 'Peluqueria 52', 'Pasaje Olvidado 789', 'Las Condes', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (188, 'Peluqueria 59', 'Avenida Recoleta 222', 'Castro', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (646, 'Peluqueria 75', 'Calle Bellavista 606', 'Las Condes', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (451, 'Peluqueria 60', 'Calle Falsa 123', 'Taltal', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (999, 'Peluqueria 55', 'Calle Londres 404', 'Lautaro', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (610, 'Peluqueria 75', 'Camino Perdido 159', 'Antofagasta', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (48, 'Peluqueria 75', 'Avenida Tobalaba 666', 'Valparaiso', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (703, 'Peluqueria 8', 'Calle Falsa 123', 'Concepcion', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (387, 'Peluqueria 96', 'Paseo Bulnes 303', 'Quilpue', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (67, 'Peluqueria 92', 'Avenida OHiggins 444', 'Puerto Varas', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (128, 'Peluqueria 76', 'Calle Falsa 123', 'Talcahuano', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (739, 'Peluqueria 18', 'Avenida Siempre Viva 456', 'Corral', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (389, 'Peluqueria 52', 'Camino Perdido 159', 'Puerto Varas', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (39, 'Peluqueria 69', 'Calle Londres 404', 'Mariquina', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (642, 'Peluqueria 40', 'Calle Suecia 555', 'Quilpue', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (102, 'Peluqueria 3', 'Camino Perdido 159', 'Villarrica', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (49, 'Peluqueria 10', 'Avenida Brasil 505', 'Corral', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (424, 'Peluqueria 81', 'Calle Londres 404', 'Mafil', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (808, 'Peluqueria 6', 'Calle Esmeralda 333', 'Mafil', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (499, 'Peluqueria 86', 'Avenida OHiggins 444', 'Quilpue', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (479, 'Peluqueria 93', 'Calle Falsa 123', 'Lautaro', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (371, 'Peluqueria 19', 'Boulevard Eterno 753', 'Rio Bueno', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (561, 'Peluqueria 68', 'Avenida Brasil 505', 'La Union', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (78, 'Peluqueria 50', 'Paseo Bulnes 303', 'Quilpue', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (283, 'Peluqueria 55', 'Avenida Matta 202', 'Las Condes', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (816, 'Peluqueria 4', 'Boulevard Eterno 753', 'Valparaiso', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (379, 'Peluqueria 94', 'Calle Esmeralda 333', 'Osorno', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (205, 'Peluqueria 88', 'Camino Perdido 159', 'Puerto Montt', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (758, 'Peluqueria 39', 'Avenida Recoleta 222', 'Lautaro', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (117, 'Peluqueria 21', 'Avenida Santa Rosa 909', 'Villa Alemana', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (844, 'Peluqueria 72', 'Calle Suecia 555', 'Maipu', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (595, 'Peluqueria 31', 'Calle Merced 111', 'Los Angeles', 'Biobio');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (487, 'Peluqueria 42', 'Avenida Siempre Viva 456', 'Santiago', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (331, 'Peluqueria 68', 'Calle Bellavista 606', 'Puerto Varas', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (438, 'Peluqueria 60', 'Calle Merced 111', 'Antofagasta', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (263, 'Peluqueria 42', 'Calle Merced 111', 'Lautaro', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (649, 'Peluqueria 26', 'Calle Esmeralda 333', 'Valdivia', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (396, 'Peluqueria 10', 'Avenida Brasil 505', 'Lanco', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (801, 'Peluqueria 56', 'Paseo Bulnes 303', 'Quilpue', 'Valparaiso');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (188, 'Peluqueria 16', 'Avenida OHiggins 444', 'Tocopilla', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (177, 'Peluqueria 2', 'Calle Bellavista 606', 'Temuco', 'Araucania');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (47, 'Peluqueria 59', 'Avenida Santa Rosa 909', 'Providencia', 'Metropolitana');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (855, 'Peluqueria 19', 'Camino Perdido 159', 'Castro', 'Los Lagos');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (554, 'Peluqueria 93', 'Avenida Tobalaba 666', 'Calama', 'Antofagasta');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (505, 'Peluqueria 65', 'Avenida Siempre Viva 456', 'Lanco', 'Los Rios');
INSERT INTO sede_pelu (id_sede, nombre_pelu, direccion_pelu, comuna_pelu, region_pelu) VALUES (39, 'Peluqueria 55', 'Avenida Matta 202', 'Las Condes', 'Metropolitana');